### ISSUE TITLE
Figure out why builds are running out of memory

### ISSUE THREAD

**Issue by devpow112** [WNProject/WNFramework#408]
I'm guessing it's linking.

**Comment by devpow112** [comment]
Try adding docker memory swapping for now to add "more" memory
```
docker run--memory-swap 1G 
```

**Comment by devpow112** [comment]
Or try adding it directly to the runner
```yml
- name: Set Swap Space
  uses: pierotofy/set-swap-space@master
  with:
    swap-size-gb: 10
```
